In [2]:
#!pip install kagglehub
#import kagglehub
import pandas as pd
# Download latest version
#path = kagglehub.dataset_download("khushikyad001/urban-tree-health-monitoring-dataset")

#print("Path to dataset files:", path)

df = pd.read_csv("c:/Users/princ/.cache/kagglehub/datasets/khushikyad001/urban-tree-health-monitoring-dataset/versions/1/urban_tree_health_monitoring.csv")
df.head()

,Tree_ID,Latitude,Longitude,Species,Height_m,Canopy_Width_m,Canopy_Condition,Disease_Symptom,Leaf_Color_Deviation,Bark_Damage_Score,...,PM2.5_ug_m3,NO2_ppb,O3_ppb,Air_Quality_Index,Urban_Zone,Year_Planted,Recent_Pruning_Year,Tree_Crown_Diameter_m,Crown_Density_%,Proximity_to_Road_m
0,TREE_00000,37.649816,-122.163649,Oak,13.76,7.52,Full,NaN,0.61,9,...,16.4,40.6,18.7,Moderate,Zone E,2011,2019.0,1.69,42.4,83.85
1,TREE_00001,37.880286,-122.101659,Oak,10.48,5.59,Full,NaN,0.29,7,...,13.5,20.8,24.8,Unhealthy,Zone C,1964,2009.0,3.83,55.7,85.16
2,TREE_00002,37.792798,-122.374766,Pine,11.93,3.37,Partial,NaN,0.80,3,...,6.7,30.0,43.7,Good,Zone C,2000,NaN,4.64,58.6,55.75
3,TREE_00003,37.739463,-122.187563,Birch,10.25,4.81,Partial,Leaf Spot,0.80,2,...,6.4,40.3,31.3,Unhealthy,Zone C,1963,2020.0,3.89,31.3,14.42
4,TREE_00004,37.562407,-122.214127,Birch,4.74,3.32,Full,Fungal Infection,0.78,7,...,15.9,25.1,39.8,Unhealthy for Sensitive Groups,Zone A,2008,2011.0,2.28,99.0,63.55

In [ ]:
def Euclidian_dist(){
    
}

Use 4 features, 30 is too much. Curse of dimensionality
calculate euclidean distance
find closest
define K
majority voting

In [ ]:
radius_mean (Size)
texture_mean (Gray-scale variation)
concavity_mean (Severity of indentations)
symmetry_mean (Shape consistency)

In [7]:
X

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039