In [1]:
#!pip install kagglehub
#import kagglehub
import pandas as pd
# Download latest version
#path = kagglehub.dataset_download("khushikyad001/urban-tree-health-monitoring-dataset")

#print("Path to dataset files:", path)

df = pd.read_csv("c:/Users/princ/.cache/kagglehub/datasets/khushikyad001/urban-tree-health-monitoring-dataset/versions/1/urban_tree_health_monitoring.csv")
df.head()

,Tree_ID,Latitude,Longitude,Species,Height_m,Canopy_Width_m,Canopy_Condition,Disease_Symptom,Leaf_Color_Deviation,Bark_Damage_Score,...,PM2.5_ug_m3,NO2_ppb,O3_ppb,Air_Quality_Index,Urban_Zone,Year_Planted,Recent_Pruning_Year,Tree_Crown_Diameter_m,Crown_Density_%,Proximity_to_Road_m
0,TREE_00000,37.649816,-122.163649,Oak,13.76,7.52,Full,NaN,0.61,9,...,16.4,40.6,18.7,Moderate,Zone E,2011,2019.0,1.69,42.4,83.85
1,TREE_00001,37.880286,-122.101659,Oak,10.48,5.59,Full,NaN,0.29,7,...,13.5,20.8,24.8,Unhealthy,Zone C,1964,2009.0,3.83,55.7,85.16
2,TREE_00002,37.792798,-122.374766,Pine,11.93,3.37,Partial,NaN,0.80,3,...,6.7,30.0,43.7,Good,Zone C,2000,NaN,4.64,58.6,55.75
3,TREE_00003,37.739463,-122.187563,Birch,10.25,4.81,Partial,Leaf Spot,0.80,2,...,6.4,40.3,31.3,Unhealthy,Zone C,1963,2020.0,3.89,31.3,14.42
4,TREE_00004,37.562407,-122.214127,Birch,4.74,3.32,Full,Fungal Infection,0.78,7,...,15.9,25.1,39.8,Unhealthy for Sensitive Groups,Zone A,2008,2011.0,2.28,99.0,63.55

In [2]:
def Euclidian_dist(p1,p2) -> float:
    dist = (abs(p1[0] - p2[0])**2 + abs(p1[1] - p2[1])**2) ** 0.5
    return dist

In [80]:
points = {}
points = dict.fromkeys(list(zip(df['Latitude'],df['Longitude'],df['Species'])),[])
Euclidian_dist(list(points.keys())[0],list(points.keys())[100])

0.32087146605825356

In [81]:
def sorting(pt):
    pt_dict = dict.fromkeys(points[pt],0)
    pt_dict = {points[pt][i]:Euclidian_dist(pt,points[pt][i]) for i in range(len(points[pt]))}
    pt_dict = dict(sorted(pt_dict.items(), key=lambda item: item[1], reverse=True))
    return list(pt_dict.keys())

In [69]:
list(pt_dict.keys())

[(37.721082830287415, -122.27021851124724, 'Willow'),
 (37.562909283271885, -122.24838979257068, 'Elm'),
 (37.61601821278497, -122.25735468296914, 'Redwood'),
 (37.65862147279599, -122.2505160278896, 'Oak'),
 (37.62391514368364, -122.11742557506936, 'Birch')]

In [82]:
points

{(37.64981604753894, -122.16364850289555, 'Oak'): [],
 (37.88028572256397, -122.10165930140433, 'Oak'): [],
 (37.79279757672456, -122.37476605060375, 'Pine'): [],
 (37.73946339367881, -122.1875629501965, 'Birch'): [],
 (37.56240745617698, -122.21412700842812, 'Birch'): [],
 (37.56239780813448, -122.08358481160586, 'Pine'): [],
 (37.52323344486728, -122.04695646975937, 'Elm'): [],
 (37.84647045830997, -122.49392161426132, 'Redwood'): [],
 (37.74044600469728, -122.1629900404706, 'Oak'): [],
 (37.78322903111842, -122.47408210044014, 'Oak'): [],
 (37.50823379771832, -122.22557066746133, 'Pine'): [],
 (37.88796394086479, -122.35618363547816, 'Pine'): [],
 (37.83297705632017, -122.34661170023892, 'Elm'): [],
 (37.58493564427131, -122.32352074827382, 'Cedar'): [],
 (37.57272998688284, -122.1893537754752, 'Birch'): [],
 (37.573361803941374, -122.3329750171656, 'Maple'): [],
 (37.62169689718382, -122.13365047470488, 'Cedar'): [],
 (37.709902572652894, -122.29773630721309, 'Willow'): [],
 (37.67277800745685, -122.46582339984502, 'Birch'): [],
 (37.61649165607922, -122.10812007875796, 'Oak'): [],
 (37.74474115788895, -122.35712083770365, 'Willow'): [],
 (37.55579754426082, -122.28361656020036, 'Cedar'): [],
 (37.61685785941409, -122.15727805838904, 'Pine'): [],
 (37.64654473731748, -122.33377192142564, 'Elm'): [],
 (37.682427993686815, -122.47170717192664, 'Birch'): [],
 (37.814070384557205, -122.3130394764936, 'Elm'): [],
 (37.57986951286335, -122.02777570865284, 'Willow'): [],
 (37.70569377536545, -122.17913280135072, 'Birch'): [],
 (37.736965827544815, -122.1642604256664, 'Redwood'): [],
 (37.518580165088, -122.18385892318118, 'Redwood'): [],
 (37.74301794076057, -122.40050393052029, 'Cedar'): [],
 (37.56820964947492, -122.29083306794884, 'Oak'): [],
 (37.52602063719412, -122.12453010081836, 'Redwood'): [],
 (37.87955421490133, -122.44931355122344, 'Redwood'): [],
 (37.886252813229824, -122.36107361195516, 'Maple'): [],
 (37.82335893924658, -122.36184044576709, 'Elm'): [],
 (37.62184550766935, -122.28399053620277, 'Elm'): [],
 (37.53906884560255, -122.0098156295289, 'Redwood'): [],
 (37.77369321060486, -122.4662487266581, 'Maple'): [],
 (37.67606099749584, -122.2406495028097, 'Elm'): [],
 (37.54881529393791, -122.41031765899388, 'Elm'): [],
 (37.69807076404451, -122.01466172729512, 'Birch'): [],
 (37.51375540844609, -122.44334824763628, 'Birch'): [],
 (37.86372816083151, -122.2981994988192, 'Maple'): [],
 (37.60351199264001, -122.1310575075827, 'Willow'): [],
 (37.76500891374159, -122.14772278598628, 'Oak'): [],
 (37.62468443043576, -122.28863568155305, 'Cedar'): [],
 (37.70802720847112, -122.32673791602365, 'Redwood'): [],
 (37.71868411173731, -122.30119381072356, 'Redwood'): [],
 (37.57394178221021, -122.36786186842068, 'Cedar'): [],
 (37.88783385110583, -122.3973335306466, 'Redwood'): [],
 (37.810053129344446, -122.25848015122055, 'Redwood'): [],
 (37.87579957662568, -122.3657331219662, 'Willow'): [],
 (37.85793094017106, -122.35626916755136, 'Elm'): [],
 (37.73915999152443, -122.17162196826273, 'Oak'): [],
 (37.868749694009246, -122.01573133415005, 'Redwood'): [],
 (37.535397000820765, -122.19818139972033, 'Maple'): [],
 (37.578393144967656, -122.46151026646751, 'Willow'): [],
 (37.518090915564215, -122.46220819307295, 'Redwood'): [],
 (37.630132132305306, -122.02428838957722, 'Maple'): [],
 (37.65547091587579, -122.35135460484634, 'Birch'): [],
 (37.60853961270956, -122.45396650695876, 'Elm'): [],
 (37.83149500366077, -122.2004777064248, 'Pine'): [],
 (37.64270133067743, -122.18817561085488, 'Redwood'): [],
 (37.61237380387495, -122.17574758994066, 'Maple'): [],
 (37.717078433263296, -122.36629898607124, 'Willow'): [],
 (37.55636968998991, -122.49244465789276, 'Elm'): [],
 (37.82087879230161, -122.01749231527276, 'Oak'): [],
 (37.52982025747191, -122.37455347715444, 'Willow'): [],
 (37.894754774640205, -122.16198685597372, 'Birch'): [],
 (37.80889790771866, -122.14668506506064, 'Cedar'): [],
 (37.57948627261367, -122.19499629146026, 'Redwood'): [],
 (37.50220884684944, -122.34354630289316, 'Oak'): [],
 (37.82618457138193, -122.36445187311796, 'Maple'): [],
 (37.78274293753905, -122.20116585864864, 'Redwood'): [],
 (37.79160286721639, -122.06695218319416, 'Maple'): [],
 (37.80850813867438, -122.0266331355383, 'Oak'): [],
 (37.529617860693634, -122.44704709779812, 'Maple'): [],
 (37.643386291417706, -122.42258569370114, 'Willow'): [],
 (37.54634762381005, -122.02763187060846, 'Elm'): [],
 (37.84524137035024, -122.1317323858326, 'Maple'): [],
 (37.74931925073102, -122.05850308758512, 'Birch'): [],
 (37.63235920994106, -122.39868368293232, 'Elm'): [],
 (37.52542334011441, -122.2062070644453, 'Willow'): [],
 (37.62439292868626, -122.14943020279128, 'Redwood'): [],
 (37.630073328810695, -122.15994405727652, 'Pine'): [],
 (37.79184247133522, -122.29592415456663, 'Redwood'): [],
 (37.75502298854209, -122.49230255415436, 'Maple'): [],
 (37.85488509703053, -122.20853697159788, 'Maple'): [],
 (37.68888597006478, -122.3734492304102, 'Birch'): [],
 (37.54783769837532, -122.27487287692855, 'Willow'): [],
 (37.7852979148892, -122.0212094924581, 'Birch'): [],
 (37.80431401944676, -122.30048234117878, 'Cedar'): [],
 (37.7245108790278, -122.0800991966678, 'Willow'): [],
 (37.808386871981824, -122.40572969712538, 'Oak'): [],
 (37.69751823854576, -122.16376975098748, 'Oak'): [],
 (37.7090931317528, -122.01149652278052, 'Oak'): [],
 (37.671016407343416, -122.44905344956354, 'Birch'): [],
 (37.51016765069764, -122.4958400288864, 'Oak'): [],
 (37.54315657079732, -122.28320860368368, 'Willow'): [],
 (37.512571674274696, -122.45368725847432, 'Oak'): [],
 (37.75456416450551, -122.12580782516189, 'Pine'): [],
 (37.62574239243053, -122.04272566807572, 'Oak'): [],
 (37.70342827646588, -122.28298951364562, 'Maple'): [],
 (37.86302658957044, -122.37064417892228, 'Cedar'): [],
 (37.59971689165955, -122.2827983404967, 'Birch'): [],
 (37.66415316921425, -122.138276091075, 'Elm'): [],
 (37.80222045541722, -122.49547291920982, 'Cedar'): [],
 (37.59151926619665, -122.20527300525764, 'Pine'): [],
 (37.53079196393152, -122.19335415755631, 'Birch'): [],
 (37.61590058116551, -122.18115587655204, 'Willow'): [],
 (37.564488514901605, -122.37898896000956, 'Redwood'): [],
 (37.87187906093703, -122.14297363831092, 'Birch'): [],
 (37.823248151825766, -122.4543042568341, 'Maple'): [],
 (37.75336150260417, -122.4003648317666, 'Willow'): [],
 (37.84858423607509, -122.06126497667276, 'Cedar'): [],
 (37.82146883075964, -122.13063842463671, 'Cedar'): [],
 (37.57462802355441, -122.49312722299432, 'Oak'): [],
 (37.85702359939599, -122.3758118698151, 'Willow'): [],
 (37.71573689676626, -122.39279675850342, 'Redwood'): [],
 (37.82297606206562, -122.36459683598152, 'Maple'): [],
 (37.8584365199694, -122.37622011486006, 'Oak'): [],
 (37.62720138998875, -122.46873685212856, 'Oak'): [],
 (37.54402076981107, -122.2705297417016, 'Redwood'): [],
 (37.59117406501677, -122.13363326260692, 'Birch'): [],
 (37.6708431154505, -122.19663413764128, 'Cedar'): [],
 (37.827205906369, -122.16356416570096, 'Oak'): [],
 (37.84429223330254, -122.45942541073188, 'Pine'): [],
 (37.50278085221248, -122.0242546449116, 'Pine'): [],
 (37.70429892103103, -122.08075408307847, 'Cedar'): [],
 (37.66696440125951, -122.09745484075216, 'Pine'): [],
 (37.58884312418829, -122.08850809747912, 'Redwood'): [],
 (37.54794614693347, -122.0336447459336, 'Birch'): [],
 (37.63504606856145, -122.22787301694316, 'Maple'): [],
 (37.87716388156501, -122.39985899106618, 'Elm'): [],
 (37.6292811728083, -122.19160819607372, 'Oak'): [],
 (37.70751624869735, -122.12855925316605, 'Elm'): [],
 (37.78120758355807, -122.131041303323, 'Maple'): [],
 (37.64545184095172, -122.23927548791656, 'Maple'): [],
 (37.888712833088384, -122.4657706403332, 'Redwood'): [],
 (37.884978917976845, -122.31444353078494, 'Birch'): [],
 (37.60071291833015, -122.03961669576832, 'Pine'): [],
 (37.69889940235695, -122.2077755451213, 'Pine'): [],
 (37.62035132392671, -122.23083402837214, 'Redwood'): [],
 (37.61393619775099, -122.3655732428089, 'Maple'): [],
 (37.51475477894181, -122.31577554004171, 'Birch'): [],
 (37.743825733591954, -122.0523269554234, 'Birch'): [],
 (37.701071609291546, -122.16676847623658, 'Cedar'): [],
 (37.5205915005, -122.10630648662384, 'Willow'): [],
 (37.61145858569464, -122.27282728846616, 'Oak'): [],
 (37.86330635438666, -122.18487639027192, 'Redwood'): [],
 (37.59582475626679, -122.3758081956284, 'Willow'): [],
 (37.55795794883649, -122.14726958485824, 'Redwood'): [],
 (37.69578110411103, -122.28619933314832, 'Pine'): [],
 (37.89426018164424, -122.27872724259262, 'Maple'): [],
 (37.5968221086046, -122.17533883771156, 'Redwood'): [],
 (37.76885421896235, -122.03185968926552, 'Redwood'): [],
 (37.80464784613149, -122.4679968266957, 'Cedar'): [],
 (37.59505501759696, -122.0876283813265, 'Elm'): [],
 (37.79128653944474, -122.3538084447939, 'Pine'): [],
 (37.6471132530877, -122.2780402727468, 'Oak'): [],
 (37.75292233223743, -122.4890433356125, 'Birch'): [],
 (37.75341188430436, -122.34947696108284, 'Maple'): [],
 (37.7143098736299, -122.24868437868491, 'Pine'): [],
 (37.53611590802176, -122.47191196132628, 'Elm'): [],
 (37.8341209982357, -122.2544521353084, 'Redwood'): [],
 (37.62831202598869, -122.0364446855708, 'Oak'): [],
 (37.57460740415994, -122.4473033909461, 'Redwood'): [],
 (37.516310056621904, -122.11777963596224, 'Oak'): [],
 (37.736357177275295, -122.295164473312, 'Cedar'): [],
 (37.77102574473691, -122.17241314273782, 'Redwood'): [],
 (37.50663513157114, -122.3698817010074, 'Pine'): [],
 (37.704837223319714, -122.42025386872932, 'Elm'): [],
 (37.59059831007917, -122.41976869286438, 'Oak'): [],
 (37.75806911616378, -122.46475402717844, 'Maple'): [],
 (37.569746571602, -122.40717664754938, 'Oak'): [],
 (37.77637509524099, -122.16789030750552, 'Elm'): [],
 (37.65469413852021, -122.05915469407825, 'Birch'): [],
 (37.87469199549469, -122.09293715720442, 'Birch'): [],
 (37.5550083776584, -122.15743284506276, 'Cedar'): [],
 (37.6364265404201, -122.44478406829444, 'Pine'): [],
 (37.54538940849624, -122.35540627685202, 'Elm'): [],
 (37.869877447311424, -122.34509656233875, 'Cedar'): [],
 (37.8509357413524, -122.3750215268012, 'Willow'): [],
 (37.60317665108606, -122.24249717014514, 'Oak'): [],
 (37.76399361841367, -122.23222309256016, 'Willow'): [],
 (37.82688888008048, -122.32155701241444, 'Oak'): [],
 (37.72208032463978, -122.32310542063178, 'Birch'): [],
 (37.7118602313424, -122.08572220104696, 'Cedar'): [],
 (37.59674091636018, -122.10535357584016, 'Birch'): [],
 (37.53724110712236, -122.34610208415964, 'Maple'): [],
 (37.85888630318133, -122.04310577806336, 'Willow'): [],
 (37.86016722286533, -122.02359249149876, 'Willow'): [],
 (37.75324058290931, -122.33662872898498, 'Birch'): [],
 (37.63561191641948, -122.32278752560347, 'Maple'): [],
 (37.63968382984506, -122.24718292328902, 'Oak'): [],
 (37.7903822715481, -122.02943959373316, 'Cedar'): [],
 (37.85884410398103, -122.06184028342884, 'Maple'): [],
 (37.85483456970604, -122.4487160187082, 'Cedar'): [],
 (37.81195021834305, -122.30363462836428, 'Willow'): [],
 (37.75681265846171, -122.22331440512512, 'Cedar'): [],
 (37.53365598599802, -122.24843376372424, 'Willow'): [],
 (37.564651485637846, -122.40306846603156, 'Maple'): [],
 (37.85942167541083, -122.07059161441592, 'Willow'): [],
 (37.74257162386383, -122.16152960850158, 'Redwood'): [],
 (37.503678820646655, -122.0810458125741, 'Pine'): [],
 (37.54058861714641, -122.07061786032529, 'Willow'): [],
 (37.76540070764322, -122.12582207316711, 'Birch'): [],
 (37.50202463353849, -122.28039469937514, 'Maple'): [],
 (37.564323220567, -122.19472662249228, 'Redwood'): [],
 (37.71949351574664, -122.41981729694012, 'Oak'): [],
 (37.77675807907708, -122.16317729126254, 'Cedar'): [],
 (37.76078450380104, -122.41037337213037, 'Redwood'): [],
 (37.58970772378422, -122.15302520474492, 'Elm'): [],
 (37.78487168853901, -122.38520091962302, 'Redwood'): [],
 (37.59489963499872, -122.4412243499249, 'Maple'): [],
 (37.63015987926371, -122.41735775492852, 'Redwood'): [],
 (37.79859656204721, -122.49900393239048, 'Redwood'): [],
 (37.759853159618885, -122.14063019107324, 'Birch'): [],
 (37.83968936419767, -122.1337994754708, 'Willow'): [],
 (37.763045156920136, -122.24253332504335, 'Cedar'): [],
 (37.727323441334185, -122.4193185994723, 'Pine'): [],
 (37.53746990713124, -122.45822283124464, 'Oak'): [],
 (37.647086321223775, -122.49043551678136, 'Pine'): [],
 (37.60608094707269, -122.4171259115174, 'Redwood'): [],
 (37.59759585735164, -122.05457223250842, 'Elm'): [],
 (37.889204221900975, -122.37923157914916, 'Maple'): [],
 (37.65723908986671, -122.3228643363914, 'Cedar'): [],
 (37.85681862207085, -122.44732725775933, 'Maple'): [],
 (37.752455450398905, -122.38881934762593, 'Birch'): [],
 (37.81792452141666, -122.2403877146099, 'Maple'): [],
 (37.70105483724208, -122.19612365845218, 'Oak'): [],
 (37.73076155385054, -122.3773238429169, 'Elm'): [],
 (37.697007077527545, -122.47113392038744, 'Pine'): [],
 (37.57809719511922, -122.3044835654363, 'Redwood'): [],
 (37.7889808461046, -122.38289831453685, 'Redwood'): [],
 (37.61230894497634, -122.3902230383851, 'Elm'): [],
 (37.50972638657258, -122.02006859864328, 'Cedar'): [],
 (37.75818891836287, -122.19184975703712, 'Maple'): [],
 (37.570844271762816, -122.22156077841396, 'Cedar'): [],
 (37.87618343374116, -122.29211244823834, 'Pine'): [],
 (37.88157143080103, -122.28552783328492, 'Cedar'): [],
 (37.86594575608818, -122.22954749808096, 'Birch'): [],
 (37.64806348010218, -122.15178509648194, 'Elm'): [],
 (37.50618264661155, -122.14892695190908, 'Pine'): [],
 (37.87132742503509, -122.41415304614728, 'Pine'): [],
 (37.67127365932693, -122.24994362396168, 'Willow'): [],
 (37.88666192761747, -122.29402095248297, 'Pine'): [],
 (37.8854479908357, -122.06473651686532, 'Willow'): [],
 (37.84120378218695, -122.18429053939082, 'Oak'): [],
 (37.61777955682784, -122.233747966792, 'Redwood'): [],
 (37.65403909144077, -122.44230267891054, 'Willow'): [],
 (37.84045466860674, -122.19718105533828, 'Elm'): [],
 (37.62676880206251, -122.44139804715988, 'Cedar'): [],
 (37.56779709867444, -122.33139671221711, 'Willow'): [],
 (37.722720504983336, -122.42857901759284, 'Pine'): [],
 (37.87446190966431, -122.15396317648782, 'Elm'): [],
 (37.77841191866999, -122.39687394308191, 'Willow'): [],
 (37.72802446803575, -122.304070313406, 'Willow'): [],
 (37.53887059750831, -122.0521626111906, 'Pine'): [],
 (37.74600289067967, -122.39784180830053, 'Birch'): [],
 (37.8960215400417, -122.2460974680206, 'Birch'): [],
 (37.55603360609461, -122.290364169417, 'Willow'): [],
 (37.70733186094549, -122.49093797947714, 'Birch'): [],
 (37.85094922877118, -122.1036209432136, 'Maple'): [],
 (37.79630744710168, -122.4654770468427, 'Pine'): [],
 (37.77880629639811, -122.26287248951152, 'Maple'): [],
 (37.78099363359484, -122.21966085253052, 'Elm'): [],
 (37.6437964604879, -122.1857867716927, 'Maple'): [],
 (37.6174367377058, -122.15568418534606, 'Elm'): [],
 (37.82374446219141, -122.37336380823864, 'Willow'): [],
 (37.82404535787167, -122.49501061167078, 'Elm'): [],
 (37.84682892743204, -122.13827816882254, 'Elm'): [],
 (37.86529622102259, -122.2321717003262, 'Cedar'): [],
 (37.70453695954438, -122.08194114839638, 'Maple'): [],
 (37.70060651787488, -122.08930581854963, 'Cedar'): [],
 (37.81931807158671, -122.07833691610604, 'Willow'): [],
 (37.7599855723111, -122.25745267001022, 'Pine'): [],
 (37.78078675090308, -122.33318580208156, 'Maple'): [],
 (37.81831706777444, -122.10422089870433, 'Pine'): [],
 (37.85600213672703, -122.27435294348535, 'Pine'): [],
 (37.63519806274061, -122.40827890179828, 'Elm'): [],
 (37.65023318105597, -122.07251299021928, 'Redwood'): [],
 (37.537592775936346, -122.05872006161384, 'Maple'): [],
 (37.73131205639847, -122.26684512192992, 'Pine'): [],
 (37.514376909518695, -122.4621501363451, 'Redwood'): [],
 (37.68623920725298, -122.30608695504154, 'Birch'): [],
 (37.71705785388303, -122.0982311702687, 'Pine'): [],
 (37.61461650085131, -122.04911298572688, 'Birch'): [],
 (37.73633330422761, -122.3982636287512, 'Maple'): [],
 (37.51220009997562, -122.46651319398735, 'Willow'): [],
 (37.514939275499685, -122.06132477343358, 'Cedar'): [],
 (37.82904022426386, -122.30529753051056, 'Maple'): [],
 (37.6440762565645, -122.22911951786622, 'Cedar'): [],
 (37.55082420506076, -122.01596709397462, 'Cedar'): [],
 (37.70889730402192, -122.46671763604289, 'Maple'): [],
 (37.80799742123944, -122.17584099627396, 'Pine'): [],
 (37.58632841099874, -122.46294728871256, 'Oak'): [],
 (37.7491561903276, -122.31226553576676, 'Pine'): [],
 (37.53413898599751, -122.09809272740328, 'Pine'): [],
 (37.52067268846744, -122.28326388362218, 'Willow'): [],
 (37.71254185262726, -122.00140882304852, 'Elm'): [],
 (37.71625404864404, -122.2204703575267, 'Elm'): [],
 (37.754971960599285, -122.33941892368202, 'Pine'): [],
 (37.79043653348906, -122.38994433704762, 'Birch'): [],
 (37.89034083178501, -122.32473973285693, 'Willow'): [],
 (37.70652013932048, -122.31373336312022, 'Cedar'): [],
 (37.629182589176494, -122.46564316113802, 'Redwood'): [],
 (37.81807447790748, -122.3152129002866, 'Elm'): [],
 (37.60833290050483, -122.2678807401304, 'Pine'): [],
 (37.67558856828225, -122.1386311238806, 'Willow'): [],
 (37.5313825525369, -122.1716352576392, 'Oak'): [],
 (37.510140297366185, -122.14561717238544, 'Birch'): [],
 (37.88505936587117, -122.49581815906156, 'Maple'): [],
 (37.83439204820488, -122.39116630020972, 'Pine'): [],
 (37.77838968243748, -122.16915785580008, 'Willow'): [],
 (37.66358117776571, -122.25800531591013, 'Pine'): [],
 (37.56931772802834, -122.49734326216584, 'Redwood'): [],
 (37.56257481706844, -122.09775267878408, 'Cedar'): [],
 (37.60009715926584, -122.11359521335484, 'Birch'): [],
 (37.719690665882446, -122.22579041850322, 'Elm'): [],
 (37.785838369080025, -122.46676833711186, 'Elm'): [],
 (37.76407895068709, -122.1167424752337, 'Elm'): [],
 (37.61197355877837, -122.20814320613432, 'Redwood'): [],
 (37.88194611226528, -122.10902001142102, 'Maple'): [],
 (37.79515876667831, -122.12412650380207, 'Willow'): [],
 (37.72174162100456, -122.09849896402108, 'Birch'): [],
 (37.74468829849374, -122.24099596679768, 'Birch'): [],
 (37.66784002497111, -122.42983774090324, 'Elm'): [],
 (37.59909239580046, -122.16442126331016, 'Elm'): [],
 (37.64238907146051, -122.18976310747402, 'Cedar'): [],
 (37.80313844418575, -122.12887340640046, 'Redwood'): [],
 (37.5057573954519, -122.41505949697464, 'Oak'): [],
 (37.54642905620277, -122.40251240004986, 'Oak'): [],
 (37.5184010568087, -122.05479524139034, 'Pine'): [],
 (37.51629152092759, -122.12501110077396, 'Pine'): [],
 (37.8421842336044, -122.04588575564983, 'Birch'): [],
 (37.781463143752006, -122.12064233941804, 'Birch'): [],
 (37.68966953163493, -122.20142234700484, 'Maple'): [],
 (37.5391336642604, -122.17293363148606, 'Maple'): [],
 (37.696646350046734, -122.05543603803, 'Oak'): [],
 (37.68938870831222, -122.21059662274403, 'Redwood'): [],
 (37.56928074796401, -122.1838043378358, 'Pine'): [],
 (37.67354065969519, -122.4217616419982, 'Oak'): [],
 (37.65940189375895, -122.26303938994197, 'Redwood'): [],
 (37.74634003922088, -122.14180144402096, 'Oak'): [],
 (37.75403746034706, -122.36452865084182, 'Pine'): [],
 (37.51812160390882, -122.39887290973772, 'Willow'): [],
 (37.64984504585059, -122.3430865958878, 'Maple'): [],
 (37.75034396628569, -122.3792496860036, 'Cedar'): [],
 (37.70125450343203, -122.3925436814818, 'Cedar'): [],
 (37.84259593647533, -122.28757457856597, 'Cedar'): [],
 (37.76347745264758, -122.04608074305824, 'Pine'): [],
 (37.56517377083257, -122.24647017663064, 'Elm'): [],
 (37.52822749896017, -122.40603980959234, 'Elm'): [],
 (37.75696771128253, -122.46151416530957, 'Elm'): [],
 (37.510604524216646, -122.15192192743103, 'Birch'): [],
 (37.73431023250939, -122.3086006177818, 'Maple'): [],
 (37.876092096569984, -122.08908452670732, 'Maple'): [],

In [83]:
k = 5
points_dist = list(points.keys())
for i in range(len(points_dist)):
    dist_arr = []
    n = []
    
    for j in range(i+1,len(points_dist)-1):
        if len(points[points_dist[j]]) > 0:
            points[points_dist[j]]= sorting(points_dist[j])
        if len(points[points_dist[i]]) > 0:
            points[points_dist[i]]= sorting(points_dist[i])
        if points_dist[j] not in points[points_dist[i]]:
            p = Euclidian_dist(points_dist[i],points_dist[j])
            if len(points[points_dist[i]]) < k:
                dist_arr.append(p)
                points[points_dist[i]].append(points_dist[j])
                if points_dist[i] not in points[points_dist[j]]:
                    for a in range(len(points[points_dist[j]])):
                        if p < Euclidian_dist(points_dist[j],points[points_dist[j]][a]):
                            points[points_dist[j]][a] = points_dist[i]
                            break
            else:
                for a in range(len(points[points_dist[i]])):
                    if points_dist[j] not in points[points_dist[i]]:
                        if p < Euclidian_dist(points[points_dist[i]][a],points_dist[i]):
                            #dist_arr[a]=p
                            points[points_dist[i]][a] = points_dist[j]
                            break
                if points_dist[i] not in points[points_dist[j]]:
                    for a in range(len(points[points_dist[j]])):
                        if p < Euclidian_dist(points_dist[j],points[points_dist[j]][a]):
                            points[points_dist[j]][a] = points_dist[i]
                            break

In [ ]:
[(37.65862147279599, -122.2505160278896, 'Oak'),
 (37.62391514368364, -122.11742557506936, 'Birch'),
 (37.61601821278497, -122.25735468296914, 'Redwood'),
 (37.562909283271885, -122.24838979257068, 'Elm'),
 (37.721082830287415, -122.27021851124724, 'Willow')]

In [ ]:
points

{(37.721082830287415, -122.27021851124724, 'Willow'): 0.12820343600463927,
 (37.562909283271885, -122.24838979257068, 'Elm'): 0.12138316131643875,
 (37.61601821278497, -122.25735468296914, 'Redwood'): 0.09961496784137987,
 (37.65862147279599, -122.2505160278896, 'Oak'): 0.08731267040097378,
 (37.62391514368364, -122.11742557506936, 'Birch'): 0.05298505333909771}

In [84]:
#find closes 5, need to sort the values put highest first
#vote
#thats the label 
points[points_dist[100]]

[(37.51537053958493, -122.46590669011728, 'Birch'),
 (37.518090915564215, -122.46220819307295, 'Redwood'),
 (37.51086696849023, -122.462552078999, 'Elm'),
 (37.514376909518695, -122.4621501363451, 'Redwood'),
 (37.512634457930254, -122.4596922974152, 'Willow')]

Use 4 features, 30 is too much. Curse of dimensionality
calculate euclidean distance
find closest
define K
majority voting

In [ ]:
radius_mean (Size)
texture_mean (Gray-scale variation)
concavity_mean (Severity of indentations)
symmetry_mean (Shape consistency)

In [7]:
X

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039